# Generated by Django 5.1.7 on 2025-04-15 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_bio_user_is_client_user_is_freelancer_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
